# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a23b3e87fd14926762a771fef0472a93add901a9f963249432e1b6dac218247a1bf58b2c228805d897414fb5e1b209763c6a3757453003f0f7db79851a3e6b

test:
  secret_key_base: 3f7b620736e32d899fcd86f5138a9192d7e474b97bc25f00d7c650b8afd3f61c7d45805d9f104dc5f4a5a6ba4e480bebc4a4c5891b01d6746f0f19ef4fcca5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
